### ISSUE TITLE
Broken highlighting of non-prefixed hex values

### ISSUE THREAD

**Issue by dkearns** [jkotlinski/forth.vim#10]
Non-prefixed hex values are incorrectly highlighted when the value does not include a decimal digit somewhere in the value.  E.g. `adde` in this line https://github.com/jkotlinski/durexforth/blob/c3892887a7181f6df6fbd26dd4d7a1ddcf3317e4/forth/sin.fs#L10

It seems that this results from an attempt to distinguish these values from other words composed of hex alpha characters.

https://github.com/jkotlinski/forth.vim/blob/fb91c5f8131ec2de46626a47157971374c43ed79/syntax/forth.vim#L188

Words that match this pattern are obviously also incorrectly matched as hex values.  E.g. `F1` in this line https://github.com/andrewtholt/minforth/blob/b26bbde742082800f433982862534e3aa209103c/examples/sha1.f#L95

It would be possible to create a hex syntax region with start and end patterns of `hex` and `decimal`, for example, but it would only work for simple examples and I'm not sure it's worth the trouble.

**Comment by jkotlinski** [comment]
Good catch. Maybe that line could simply be removed?

**Comment by jkotlinski** [comment]
I removed that line now, in testing branch. Too many false matches.
