### ISSUE TITLE
Stop startling users of LOCALS|

### ISSUE THREAD

**Issue by dkearns** [jkotlinski/forth.vim#39]
Highlighting `LOCALS|` as an error by default seems a bit over the top to me.   Is there some meaningful Forth history that justifies this?

I think highlighting obsolete words should be done more generally, if it's a good idea at all, and should probably be an opt-in feature.

**Comment by jkotlinski** [comment]
`LOCALS|` was added to the ANS-94 Forth standard, then turned out to be not a good idea, and was marked as obsolete in Forth-2012.

I agree, it does not make sense to mark it as an error, just because it is marked as obsolete.
