### ISSUE TITLE
highlighting lost when pressing `o`

### ISSUE THREAD

**Issue by jkotlinski** [jkotlinski/forth.vim#43]
Repro: Open a file with following content, then, type 'o' on the first line.
```
\ foo
( bar
\ baz
)
```
What happens: The `)` changes color.

Expected: The `)` would remain part of a multi-line comment.

**Comment by jkotlinski** [comment]
It seems this is fixed by changing `syn sync ccomment` to `syn sync fromstart`.

Any thoughts @dkearns ?

**Comment by jkotlinski** [comment]
Changing `syn sync ccomment` to `syn sync minlines=50` also seems fine.

**Comment by dkearns** [comment]
`ccomment` is for C comments.  I think it was cargo-culted into a number of the earlier syntax files.

It's possible to sync on the comment delimiters with `syn sync match` but it may be a bit tricky.

`fromstart` would probably work well as Forth files don't tend, in general, to be that large but it is noticeably slower with `'relativenumber'` set when testing with something silly like scrolling pages with `j`.

So, I'd probably just use `minlines` and there is somewhat of a convention to allow that to be configurable with a `forth_minlines` variable.  E.g., https://github.com/vim/vim/blob/50809a45ebde327cb6fdcc727d7466e926aed713/runtime/syntax/c.vim#L458
