### ISSUE TITLE
Update RELEASING.md

### ISSUE THREAD

**Issue by jkotlinski** [jkotlinski/forth.vim#52]
E-mailing bram@moolenaar.net is no longer appropriate.

**Comment by dkearns** [comment]
The current options appear to be a PR against the Vim repo or emailing the vim-dev mailing list.

**Comment by jkotlinski** [comment]
Sounds good. Speaking of that, when do you think is a good time for next release? Anything you want to get in?

The forth.vim in mainline Vim is from 2023-01-12, which is actually newer than I expected. So maybe there is no stress for a new release.

**Comment by dkearns** [comment]
We may as well try and finish the existing PRs as long as we don't miss Vim 9.1.  I'll keep an eye on it.

**Comment by dkearns** [comment]
There's an imminent Vim 9.1 release so it would be a good idea to submit what we have.  I don't think I'll get the rest before then.

**Comment by jkotlinski** [comment]
Sounds great, would you like to submit?

ons 30 aug. 2023 kl. 15:47 skrev dkearns ***@***.***>:

**Comment by dkearns** [comment]
Sure, I'll do that today.  Thanks.
